# Created by: Jonathan Anderson <jonathan@FreeBSD.org>
# $FreeBSD$

PORTNAME=	git-cola
PORTVERSION=	2.2.1
DISTVERSIONPREFIX=	v
CATEGORIES=	devel

MAINTAINER=	ports@FreeBSD.org
COMMENT=	Sleek and powerful Git GUI

LICENSE=	GPLv2

USE_GITHUB=	yes
GH_ACCOUNT=	git-cola
GH_PROJECT=	git-cola

USES=		desktop-file-utils gettext gmake python
INSTALLS_ICONS=	YES

MAKE_FLAGS=	"prefix=${PREFIX}"

.include <bsd.port.mk>
